### ISSUE TITLE
Zoom security concerns

### ISSUE THREAD

**Issue by rube-de** [Pezmc/distant-socializing#2]
I recommend to remove from the video call list.

there are enough articles about their problems:
https://theintercept.com/2020/04/03/zooms-encryption-is-not-suited-for-secrets-and-has-surprising-links-to-china-researchers-discover/
https://www.theguardian.com/technology/2020/apr/02/zoom-technology-security-coronavirus-video-conferencing
https://edition.cnn.com/2020/04/04/us/nyc-schools-zoom-online-security/index.html

**Comment by Pezmc** [comment]
Thank you for the extra information! I've added a warning to the doc and linked to this thread if there's any other information you'd like to share!
